version: '3'
services:
  app:
    build: .
    environment:
      - DB_PORT=3307
      - DB_NAME=java_cloud_db
      - DB_USER=root
      - DB_PASS=1234
    ports:
      - 3301:3307
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: java_cloud_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
volumes:
  mysql_data: